version: "3"

services:
  i_cal_duplicator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        initial_otp: "${INITIAL_OTP}"
    container_name: ical-buddy
    ports:
      - "127.0.0.1:5000:5000"
    restart: on-failure
    env_file:
      - .env
    tty: true